version: '3'
services:
  arknights_project:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    build:
      context: .
      dockerfile: Dockerfile
    image: node-20.16.0/arknights_project
    ports:
      - '${APP_PORT:-4000}:4000'

    volumes:
      - '.:/usr/src/arknights_project'
    networks:
      - arknights_project

  redis:
    container_name: "redis-arknights_project"
    image: 'redis:alpine'
    command: redis-server --save 20 1
    restart: always
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'arknights_project-redis:/data'
    networks:
      - arknights_project
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s

  postgres:
    image: postgres:17
    restart: always
    container_name: 'postgres-arknights_project'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: posts-db
    ports:
      - "5432:5432"


networks:
  arknights_project:
    driver: bridge
volumes:
  arknights_project-redis:
    driver: local
